-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-25 16:07:23 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on 
SPOOL oo_schema_output.txt

--student id: 33413126
--student name: Cheuk Hin Chester Man

DROP TABLE ADDRESS CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     address_id       VARCHAR2 (7)  NOT NULL , 
     address_street   VARCHAR2 (50)  NOT NULL , 
     address_town     VARCHAR2 (50)  NOT NULL , 
     address_postcode VARCHAR2 (10)  NOT NULL , 
     address_country  VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.address_id IS 'address id (surrogate PK)' 
;

COMMENT ON COLUMN ADDRESS.address_street IS 'address street' 
;

COMMENT ON COLUMN ADDRESS.address_town IS 'address town' 
;

COMMENT ON COLUMN ADDRESS.address_postcode IS 'address postcode' 
;

COMMENT ON COLUMN ADDRESS.address_country IS 'address_country' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( address_id ) ;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_NK UNIQUE ( address_street , address_town , address_postcode , address_country ) ;

CREATE TABLE CABIN 
    ( 
     cabin_no             NUMBER (7)  NOT NULL , 
     ship_code            NUMBER (7)  NOT NULL , 
     cabin_sleep_capacity NUMBER (7)  NOT NULL , 
     cabin_class          VARCHAR2 (10)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabin_class 
    CHECK (cabin_class IN ('B', 'I', 'OV', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_no IS 'cabin number' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'ship code' 
;

COMMENT ON COLUMN CABIN.cabin_sleep_capacity IS 'cabin sleep capacity' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'cabin class I-Interior, OV-Ocean view, B-Balcony, S-Suite' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_no, ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code NUMBER (7)  NOT NULL , 
     country_name VARCHAR2 (30)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'country code' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'country name' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id               NUMBER (7)  NOT NULL , 
     cruise_name             VARCHAR2 (20)  NOT NULL , 
     cruise_description      VARCHAR2 (100)  NOT NULL , 
     cruise_depart_date      DATE  NOT NULL , 
     cruise_deport_time      DATE  NOT NULL , 
     cruise_departurearrival VARCHAR2 (7)  NOT NULL , 
     cruise_datetime         DATE  NOT NULL , 
     cruise_cost_per_person  NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'name of the cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_description IS 'description of the cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_depart_date IS 'depart date of the cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_deport_time IS 'cruise depart time' 
;

COMMENT ON COLUMN CRUISE.cruise_departurearrival IS 'departure/arrival of cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_datetime IS 'cruise date/time' 
;

COMMENT ON COLUMN CRUISE.cruise_cost_per_person IS 'cruise cost per person' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE MANIFEST 
    ( 
     passenger_id         VARCHAR2 (7)  NOT NULL , 
     passenger_board_date DATE  NOT NULL , 
     passenger_board_time DATE  NOT NULL 
    ) 
;

COMMENT ON COLUMN MANIFEST.passenger_id IS 'passenger id' 
;

COMMENT ON COLUMN MANIFEST.passenger_board_date IS 'board date of the passenger ' 
;

COMMENT ON COLUMN MANIFEST.passenger_board_time IS 'board time of the passenger' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE OPERATOR 
    ( 
     operator_id       NUMBER (7)  NOT NULL , 
     operator_name     NUMBER (10)  NOT NULL , 
     operator_ceo_name VARCHAR2 (50)  NOT NULL , 
     ship_code         NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.operator_id IS 'operator id ' 
;

COMMENT ON COLUMN OPERATOR.operator_name IS 'operator name' 
;

COMMENT ON COLUMN OPERATOR.operator_ceo_name IS 'operator ceo name' 
;

COMMENT ON COLUMN OPERATOR.ship_code IS 'ship code' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( operator_id ) ;

CREATE TABLE PASSENGER 
    ( 
     passenger_id         VARCHAR2 (7)  NOT NULL , 
     ship_code            NUMBER (7)  NOT NULL , 
     guardian_id          VARCHAR2 (7) , 
     passenger_first_name VARCHAR2 (50)  NOT NULL , 
     passenger_last_name  VARCHAR2 (50)  NOT NULL , 
     passenger_gender     VARCHAR2 (10)  NOT NULL , 
     passenger_birth_date DATE  NOT NULL , 
     passenger_phone_no   NUMBER (20) , 
     address_id           VARCHAR2 (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PASSENGER.passenger_id IS 'passenger id' 
;

COMMENT ON COLUMN PASSENGER.ship_code IS 'ship code' 
;

COMMENT ON COLUMN PASSENGER.guardian_id IS 'passenger id' 
;

COMMENT ON COLUMN PASSENGER.passenger_first_name IS 'first name of the passenger' 
;

COMMENT ON COLUMN PASSENGER.passenger_last_name IS 'last name of the passenger' 
;

COMMENT ON COLUMN PASSENGER.passenger_gender IS 'gender of the passenger' 
;

COMMENT ON COLUMN PASSENGER.passenger_birth_date IS 'passenger birth date' 
;

COMMENT ON COLUMN PASSENGER.passenger_phone_no IS 'passenger phone number' 
;

COMMENT ON COLUMN PASSENGER.address_id IS 'address id (surrogate PK)' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE PORT 
    ( 
     port_code       NUMBER (7)  NOT NULL , 
     port_name       VARCHAR2 (50)  NOT NULL , 
     port_latitude   NUMBER (30) , 
     port_longtitude NUMBER (30) , 
     country_code    NUMBER (7) , 
     cruise_id       NUMBER (7) 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'port code' 
;

COMMENT ON COLUMN PORT.port_name IS 'port name' 
;

COMMENT ON COLUMN PORT.port_longtitude IS 'port longtitude' 
;

COMMENT ON COLUMN PORT.country_code IS 'country code' 
;

COMMENT ON COLUMN PORT.cruise_id IS 'cruise id' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code               NUMBER (7)  NOT NULL , 
     operator_id             NUMBER (7)  NOT NULL , 
     cruise_id               NUMBER (7)  NOT NULL , 
     ship_name               VARCHAR2 (50)  NOT NULL , 
     ship_commission_date    DATE  NOT NULL , 
     ship_tonnage            NUMBER (7)  NOT NULL , 
     ship_max_guest_capacity NUMBER (7) , 
     ship_register_country   VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'ship code' 
;

COMMENT ON COLUMN SHIP.operator_id IS 'operator id ' 
;

COMMENT ON COLUMN SHIP.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'ship name' 
;

COMMENT ON COLUMN SHIP.ship_commission_date IS 'ship commission date' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'ship toonage' 
;

COMMENT ON COLUMN SHIP.ship_max_guest_capacity IS 'ship maximum guest capacity' 
;

COMMENT ON COLUMN SHIP.ship_register_country IS 'ship register country' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT address_passenger FOREIGN KEY 
    ( 
     address_id
    ) 
    REFERENCES ADDRESS 
    ( 
     address_id
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT country_port_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT cruise_port_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT cruise_ship_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT operator_ship_fk FOREIGN KEY 
    ( 
     operator_id
    ) 
    REFERENCES OPERATOR 
    ( 
     operator_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT passenger_guardian FOREIGN KEY 
    ( 
     guardian_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT passenger_manifest_fk FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT ship_passenger_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

SPOOL off 
set echo off 

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
